# Generated by Django 2.2.14 on 2020-07-16 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20200716_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id_meetup', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='meetups/')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='published_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_date',
        ),
        migrations.AddField(
            model_name='event',
            name='id_meetup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetup.Meetup'),
            preserve_default=False,
        ),
    ]
