# Generated by Django 2.2.14 on 2020-07-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_auto_20200716_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='id_meetup',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
