# Generated by Django 2.2.14 on 2020-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_auto_20200716_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='meetup.Meetup'),
        ),
    ]
