# Generated by Django 2.2.14 on 2020-07-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_auto_20200717_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.Meetup'),
        ),
    ]
