# Generated by Django 2.2.14 on 2020-07-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_auto_20200717_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetup.Meetup'),
        ),
    ]
